# Generated by Django 5.2.3 on 2025-06-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Studend",
        ),
    ]
