# Generated by Django 5.2.3 on 2025-06-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.CharField(max_length=10)),
                ("emp_name", models.CharField(max_length=100)),
                ("designations", models.CharField(max_length=100)),
            ],
        ),
    ]
